spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
file:
  dir: /root/backend/file/